// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzinylpjxzgdqbrvolhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6aW55bHBqeHpnZHFicnZvbGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODIwOTIsImV4cCI6MjA2ODY1ODA5Mn0.vAlTA4Ezby-golC0iCaPfseJIFoZPnWGXF1YrLysnNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});